---
- hosts: all
  become: yes
  vars:
   created_username: {{ username }}
  
  tasks:

    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

    - name: Enable guest agent service
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: yes

    - name: Start guest agent service, if not started
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started

    - name: install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: true

    - name: notify via Gotify
      uri:
        url: 'http://{{ IP_Address }}:{{ port }}/message?token={{ token }}'
        method: POST
        body:
          title:
            content: Initial-Config Complete (VM)
          message: 
            content: The initial configuration playbook has completed for {{ ansible_host }} and the guest agent has been loaded. 
          priority:
            content: '5'
        body_format: form-multipart
      register: result

...
